version: '3.1'
services:
  db:
    image: arm64v8/mysql:oracle
   
   
    environment:
      MYSQL_ROOT_PASSWORD: example


  adminer:
    image: adminer
    
    ports:
      - 8080:8080

  node:
    image: netpos_storm

    ports: 
    - 3000:80
volumes: 
  datavol:


